### ISSUE TITLE
Segmentation fault (core dumped) when I run the Full Node or ckpool Proxy Node "ckpool -N"

### ISSUE THREAD

**Issue by Maleksh** [ctubio/ckpool#3]
I am getting Segmentation fault (core dumped) when I run the Full Node or ckpool Proxy Node "ckpool -N" as per the below error:
ubento@ubuntu1604:~/ckpool/src$ sudo ckpool -N
[2018-03-29 15:35:12.398] cknode generator starting
[2018-03-29 15:35:12.398] cknode stratifier starting
[2018-03-29 15:35:12.400] cknode stratifier ready
[2018-03-29 15:35:12.399] cknode connector starting
[2018-03-29 15:35:12.401] cknode connector ready
[2018-03-29 15:35:12.466] Connected to bitcoind: 172.31.223.113:8332
Segmentation fault (core dumped)
ubento@ubuntu1604:~/ckpool/src$

I installed on Ubuntu 16.04 using the below commands sequence

sudo apt-get update -y
sudo apt-get dist-upgrade -y
sudo apt-get install build-essential -y
git clone https://bitbucket.org/ckolivas/ckpool/src ckpool
cd ./ubento/ckpool/
sudo apt-get install build-essential yasm libpq-dev libgsl-dev autoconf automake libtool -y
./autogen.sh
./configure --without-ckdb
make
sudo make install
cd ./ubento/ckpool/src/
ckpool -N

Nothing work so far, only passthrough proxy mode working,

**Comment by zurylostboys** [comment]
Passthroughs can only talk to full ckpools, not proxies.

**Comment by ctubio** [comment]
note this is a dumb mirror; for support on ckpool:
```
Support and live discussion on IRC: irc.freenode.net #ckpool
```
^from http://ckpool.org/

**Comment by ctubio** [comment]
btw, dont use sudo while running any user app, like ckpool..
