### ISSUE TITLE
Failed to find Bitcoind

### ISSUE THREAD

**Issue by Keldo** [ctubio/ckpool#4]
I have Bitcoind Running with w RPC use/pass but ckpool is unable to find it.
No Firewalls currently established
ckpool in full mode does not find the bitcoin daemon
in -N same thing
in -P unable to connect to your daemon

**Comment by ctubio** [comment]
wrong configs

**Comment by ctubio** [comment]
note this is a dumb mirror; for support on ckpool:
```
Support and live discussion on IRC: irc.freenode.net #ckpool
```
^from http://ckpool.org/
