### ISSUE TITLE
Having issue installing...m4 directory missing.

### ISSUE THREAD

**Issue by jumper-d-1981** [ctubio/ckpool#5]
Hello.
I was able to install this and run the proxy yesterday but for some reason today it is not working.  I used Ubuntu server yesterday and today i am using debian.  I was hoping to run this on a pi...and wanted to test...hoping to connect several devices to it for mining.

This is the output I get after running the git clone command, and the ./autogen.sh command.  If I continue and pretend nothing is wrong I cannot start the proxy...

pi@raspberrypi:~ $ git clone https://github.com/ctubio/ckpool
Cloning into 'ckpool'...
remote: Enumerating objects: 16325, done.
remote: Total 16325 (delta 0), reused 0 (delta 0), pack-reused 16325
Receiving objects: 100% (16325/16325), 3.60 MiB | 647.00 KiB/s, done.
Resolving deltas: 100% (12223/12223), done.
pi@raspberrypi:~ $ cd ./ckpool
pi@raspberrypi:~/ckpool $ ./autogen.sh
aclocal: warning: couldn't open directory 'm4': No such file or directory
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
libtoolize: and rerunning libtoolize and aclocal.
libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
aclocal: warning: couldn't open directory 'm4': No such file or directory
configure.ac:11: installing './compile'
configure.ac:12: installing './config.guess'
configure.ac:12: installing './config.sub'
configure.ac:5: installing './install-sh'
configure.ac:5: installing './missing'
src/Makefile.am: installing './depcomp'
libtoolize: putting auxiliary files in '.'.
libtoolize: copying file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: copying file 'm4/libtool.m4'
libtoolize: copying file 'm4/ltoptions.m4'
libtoolize: copying file 'm4/ltsugar.m4'
libtoolize: copying file 'm4/ltversion.m4'
libtoolize: copying file 'm4/lt~obsolete.m4'
configure.ac:10: installing './compile'
configure.ac:3: installing './config.guess'
configure.ac:3: installing './config.sub'
configure.ac:8: installing './install-sh'
configure.ac:8: installing './missing'
src/Makefile.am: installing './depcomp'
pi@raspberrypi:~/ckpool $

**Comment by Kleiner-bmw** [comment]
If you're on a raspberry pi try it first with raspberry pi os and if it works there and everything else you want works just use raspberry pi os it works better fir my pi5 then ubunto wich also includes kali linux hope i could help ya for more questions please just ask im willing to help

**Comment by Kleiner-bmw** [comment]
Hey maybe try the same things on raspberry os 32bit,64bit or lite maybe it works there and when your on raspberry os try to go to the settings and put things like ssh and that on "ON" it could be that i hope could help

**Comment by ctubio** [comment]
note this is a dumb mirror; for support on ckpool:
```
Support and live discussion on IRC: irc.freenode.net #ckpool
```
^from http://ckpool.org/
